[test]
pathIgnorePatterns = ["fixtures/**", "fixture/**"]
coverage = true
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["src/__tests__/**"]
concurrentTestGlob = "**/*.test.ts"
onlyFailures = true

[install]
linker = "isolated"

[run]
bun = true
